# Image preprocessing & augmentation
AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # ResNet50 input
BATCH_SIZE: 16

# Training configuration
EPOCHS: 15
CLASSES: 4
LEARNING_RATE: 0.0001
INCLUDE_TOP: False
WEIGHTS: imagenet
